blank_issues_enabled: false
contact_links:
  - name: "\U0001F64B Get Help"
    url: https://gitter.im/pelias/pelias
    about: Ask for help from other members of the Pelias community in our group chat.
  - name: "\U0001F680 Geocode Earth Cloud"
    url: https://geocode.earth
    about: Sign up for an API key and get started with Pelias instantly.
  - name: "\U0001F454 Commercial Support"
    url: https://geocode.earth
    about: Consult the project founders about running Pelias in production environments.
